import type { UserRole } from '@/api/types/common'

/**
 * Route names constants
 */
export const ROUTE_NAMES = {
  // Auth
  LOGIN: 'Login',
  
  // Main
  DASHBOARD: 'Dashboard',
  
  // Materials
  MATERIALS_LIST: 'MaterialsList',
  MATERIAL_CREATE: 'MaterialCreate',
  MATERIAL_EDIT: 'MaterialEdit',
  
  // Purchases
  PURCHASES_LIST: 'PurchasesList',
  PURCHASE_CREATE: 'PurchaseCreate',
  PURCHASE_EDIT: 'PurchaseEdit',
  
  // Objects
  OBJECTS_LIST: 'ObjectsList',
  OBJECT_CREATE: 'ObjectCreate',
  OBJECT_EDIT: 'ObjectEdit',
  
  // Units
  UNITS_LIST: 'UnitsList',
  UNIT_CREATE: 'UnitCreate',
  UNIT_EDIT: 'UnitEdit',
  
  // Employees
  EMPLOYEES_LIST: 'EmployeesList',
  EMPLOYEE_CREATE: 'EmployeeCreate',
  EMPLOYEE_EDIT: 'EmployeeEdit',
  
  // Suppliers
  SUPPLIERS_LIST: 'SuppliersList',
  SUPPLIER_CREATE: 'SupplierCreate',
  SUPPLIER_EDIT: 'SupplierEdit',
  
  // Stocks
  STOCKS_LIST: 'StocksList',
  STOCK_CREATE: 'StockCreate',
  STOCK_EDIT: 'StockEdit',
  
  // WriteOffs
  WRITEOFFS_LIST: 'WriteOffsList',
  WRITEOFF_CREATE: 'WriteOffCreate',
  WRITEOFF_EDIT: 'WriteOffEdit',
  
  // Archive
  ARCHIVE_LIST: 'ArchiveList',
  
  // Reports
  REPORT_BY_PERIOD: 'ReportByPeriod',
  REPORT_BY_OBJECT: 'ReportByObject',
  REPORT_BY_MATERIAL: 'ReportByMaterial',
  REPORT_BY_RESPONSIBLE: 'ReportByResponsible',
  
  // Import
  IMPORT_PURCHASES: 'ImportPurchases',
  
  // Error
  NOT_FOUND: 'NotFound'
} as const

/**
 * Route paths constants
 */
export const ROUTE_PATHS = {
  // Auth
  LOGIN: '/login',
  
  // Main
  DASHBOARD: '/',
  
  // Materials
  MATERIALS_LIST: '/materials',
  MATERIAL_CREATE: '/materials/create',
  MATERIAL_EDIT: '/materials/:id/edit',
  
  // Purchases
  PURCHASES_LIST: '/purchases',
  PURCHASE_CREATE: '/purchases/create',
  PURCHASE_EDIT: '/purchases/:id/edit',
  
  // Objects
  OBJECTS_LIST: '/objects',
  OBJECT_CREATE: '/objects/create',
  OBJECT_EDIT: '/objects/:id/edit',
  
  // Units
  UNITS_LIST: '/units',
  UNIT_CREATE: '/units/create',
  UNIT_EDIT: '/units/:id/edit',
  
  // Employees
  EMPLOYEES_LIST: '/employees',
  EMPLOYEE_CREATE: '/employees/create',
  EMPLOYEE_EDIT: '/employees/:id/edit',
  
  // Suppliers
  SUPPLIERS_LIST: '/suppliers',
  SUPPLIER_CREATE: '/suppliers/create',
  SUPPLIER_EDIT: '/suppliers/:id/edit',
  
  // Stocks
  STOCKS_LIST: '/stocks',
  STOCK_CREATE: '/stocks/create',
  STOCK_EDIT: '/stocks/:id/edit',
  
  // WriteOffs
  WRITEOFFS_LIST: '/writeoffs',
  WRITEOFF_CREATE: '/writeoffs/create',
  WRITEOFF_EDIT: '/writeoffs/:id/edit',
  
  // Archive
  ARCHIVE_LIST: '/archive',
  
  // Reports
  REPORT_BY_PERIOD: '/reports/by-period',
  REPORT_BY_OBJECT: '/reports/by-object',
  REPORT_BY_MATERIAL: '/reports/by-material',
  REPORT_BY_RESPONSIBLE: '/reports/by-responsible',
  
  // Import
  IMPORT_PURCHASES: '/import'
} as const

/**
 * Route categories
 */
export const ROUTE_CATEGORIES = {
  MAIN: 'main',
  INVENTORY: 'inventory',
  PURCHASES: 'purchases',
  OBJECTS: 'objects',
  SUPPLIERS: 'suppliers',
  USERS: 'users',
  SETTINGS: 'settings',
  ARCHIVE: 'archive',
  REPORTS: 'reports',
  IMPORT: 'import',
  AUTH: 'auth'
} as const

/**
 * Role-based route access
 */
export const ROLE_ROUTES: Record<UserRole, string[]> = {
  admin: [
    ROUTE_NAMES.DASHBOARD,
    ROUTE_NAMES.MATERIALS_LIST,
    ROUTE_NAMES.MATERIAL_CREATE,
    ROUTE_NAMES.MATERIAL_EDIT,
    ROUTE_NAMES.PURCHASES_LIST,
    ROUTE_NAMES.PURCHASE_CREATE,
    ROUTE_NAMES.PURCHASE_EDIT,
    ROUTE_NAMES.OBJECTS_LIST,
    ROUTE_NAMES.OBJECT_CREATE,
    ROUTE_NAMES.OBJECT_EDIT,
    ROUTE_NAMES.UNITS_LIST,
    ROUTE_NAMES.UNIT_CREATE,
    ROUTE_NAMES.UNIT_EDIT,
    ROUTE_NAMES.EMPLOYEES_LIST,
    ROUTE_NAMES.EMPLOYEE_CREATE,
    ROUTE_NAMES.EMPLOYEE_EDIT,
    ROUTE_NAMES.SUPPLIERS_LIST,
    ROUTE_NAMES.SUPPLIER_CREATE,
    ROUTE_NAMES.SUPPLIER_EDIT,
    ROUTE_NAMES.STOCKS_LIST,
    ROUTE_NAMES.STOCK_CREATE,
    ROUTE_NAMES.STOCK_EDIT,
    ROUTE_NAMES.WRITEOFFS_LIST,
    ROUTE_NAMES.WRITEOFF_CREATE,
    ROUTE_NAMES.WRITEOFF_EDIT,
    ROUTE_NAMES.ARCHIVE_LIST,
    ROUTE_NAMES.REPORT_BY_PERIOD,
    ROUTE_NAMES.REPORT_BY_OBJECT,
    ROUTE_NAMES.REPORT_BY_MATERIAL,
    ROUTE_NAMES.REPORT_BY_RESPONSIBLE,
    ROUTE_NAMES.IMPORT_PURCHASES
  ],
  director: [
    ROUTE_NAMES.DASHBOARD,
    ROUTE_NAMES.MATERIALS_LIST,
    ROUTE_NAMES.MATERIAL_CREATE,
    ROUTE_NAMES.MATERIAL_EDIT,
    ROUTE_NAMES.PURCHASES_LIST,
    ROUTE_NAMES.PURCHASE_CREATE,
    ROUTE_NAMES.PURCHASE_EDIT,
    ROUTE_NAMES.OBJECTS_LIST,
    ROUTE_NAMES.OBJECT_CREATE,
    ROUTE_NAMES.OBJECT_EDIT,
    ROUTE_NAMES.UNITS_LIST,
    ROUTE_NAMES.UNIT_CREATE,
    ROUTE_NAMES.UNIT_EDIT,
    ROUTE_NAMES.EMPLOYEES_LIST,
    ROUTE_NAMES.EMPLOYEE_CREATE,
    ROUTE_NAMES.EMPLOYEE_EDIT,
    ROUTE_NAMES.SUPPLIERS_LIST,
    ROUTE_NAMES.SUPPLIER_CREATE,
    ROUTE_NAMES.SUPPLIER_EDIT,
    ROUTE_NAMES.STOCKS_LIST,
    ROUTE_NAMES.STOCK_CREATE,
    ROUTE_NAMES.STOCK_EDIT,
    ROUTE_NAMES.WRITEOFFS_LIST,
    ROUTE_NAMES.WRITEOFF_CREATE,
    ROUTE_NAMES.WRITEOFF_EDIT,
    ROUTE_NAMES.ARCHIVE_LIST,
    ROUTE_NAMES.REPORT_BY_PERIOD,
    ROUTE_NAMES.REPORT_BY_OBJECT,
    ROUTE_NAMES.REPORT_BY_MATERIAL,
    ROUTE_NAMES.REPORT_BY_RESPONSIBLE,
    ROUTE_NAMES.IMPORT_PURCHASES
  ],
  coordinator: [
    ROUTE_NAMES.DASHBOARD,
    ROUTE_NAMES.MATERIALS_LIST,
    ROUTE_NAMES.MATERIAL_CREATE,
    ROUTE_NAMES.MATERIAL_EDIT,
    ROUTE_NAMES.PURCHASES_LIST,
    ROUTE_NAMES.PURCHASE_CREATE,
    ROUTE_NAMES.PURCHASE_EDIT,
    ROUTE_NAMES.OBJECTS_LIST,
    ROUTE_NAMES.OBJECT_CREATE,
    ROUTE_NAMES.OBJECT_EDIT,
    ROUTE_NAMES.UNITS_LIST,
    ROUTE_NAMES.UNIT_CREATE,
    ROUTE_NAMES.UNIT_EDIT,
    ROUTE_NAMES.EMPLOYEES_LIST,
    ROUTE_NAMES.EMPLOYEE_CREATE,
    ROUTE_NAMES.EMPLOYEE_EDIT,
    ROUTE_NAMES.SUPPLIERS_LIST,
    ROUTE_NAMES.SUPPLIER_CREATE,
    ROUTE_NAMES.SUPPLIER_EDIT,
    ROUTE_NAMES.STOCKS_LIST,
    ROUTE_NAMES.STOCK_CREATE,
    ROUTE_NAMES.STOCK_EDIT,
    ROUTE_NAMES.WRITEOFFS_LIST,
    ROUTE_NAMES.WRITEOFF_CREATE,
    ROUTE_NAMES.WRITEOFF_EDIT,
    ROUTE_NAMES.ARCHIVE_LIST,
    ROUTE_NAMES.REPORT_BY_PERIOD,
    ROUTE_NAMES.REPORT_BY_OBJECT,
    ROUTE_NAMES.REPORT_BY_MATERIAL,
    ROUTE_NAMES.REPORT_BY_RESPONSIBLE,
    ROUTE_NAMES.IMPORT_PURCHASES
  ],
  site_manager: [
    ROUTE_NAMES.DASHBOARD,
    ROUTE_NAMES.MATERIALS_LIST,
    ROUTE_NAMES.MATERIAL_CREATE,
    ROUTE_NAMES.MATERIAL_EDIT,
    ROUTE_NAMES.PURCHASES_LIST,
    ROUTE_NAMES.PURCHASE_CREATE,
    ROUTE_NAMES.PURCHASE_EDIT,
    ROUTE_NAMES.OBJECTS_LIST,
    ROUTE_NAMES.OBJECT_CREATE,
    ROUTE_NAMES.OBJECT_EDIT,
    ROUTE_NAMES.SUPPLIERS_LIST,
    ROUTE_NAMES.SUPPLIER_CREATE,
    ROUTE_NAMES.SUPPLIER_EDIT,
    ROUTE_NAMES.STOCKS_LIST,
    ROUTE_NAMES.STOCK_CREATE,
    ROUTE_NAMES.STOCK_EDIT,
    ROUTE_NAMES.WRITEOFFS_LIST,
    ROUTE_NAMES.WRITEOFF_CREATE,
    ROUTE_NAMES.WRITEOFF_EDIT,
    ROUTE_NAMES.REPORT_BY_PERIOD,
    ROUTE_NAMES.REPORT_BY_OBJECT,
    ROUTE_NAMES.REPORT_BY_MATERIAL,
    ROUTE_NAMES.REPORT_BY_RESPONSIBLE
  ],
  brigadier: [
    ROUTE_NAMES.DASHBOARD,
    ROUTE_NAMES.MATERIALS_LIST,
    ROUTE_NAMES.PURCHASES_LIST,
    ROUTE_NAMES.PURCHASE_CREATE,
    ROUTE_NAMES.PURCHASE_EDIT,
    ROUTE_NAMES.OBJECTS_LIST,
    ROUTE_NAMES.SUPPLIERS_LIST,
    ROUTE_NAMES.SUPPLIER_CREATE,
    ROUTE_NAMES.SUPPLIER_EDIT,
    ROUTE_NAMES.STOCKS_LIST,
    ROUTE_NAMES.STOCK_CREATE,
    ROUTE_NAMES.STOCK_EDIT,
    ROUTE_NAMES.WRITEOFFS_LIST,
    ROUTE_NAMES.WRITEOFF_CREATE,
    ROUTE_NAMES.WRITEOFF_EDIT
  ],
  buyer: [
    ROUTE_NAMES.DASHBOARD,
    ROUTE_NAMES.MATERIALS_LIST,
    ROUTE_NAMES.PURCHASES_LIST,
    ROUTE_NAMES.PURCHASE_CREATE,
    ROUTE_NAMES.PURCHASE_EDIT,
    ROUTE_NAMES.OBJECTS_LIST,
    ROUTE_NAMES.SUPPLIERS_LIST,
    ROUTE_NAMES.SUPPLIER_CREATE,
    ROUTE_NAMES.SUPPLIER_EDIT
  ]
}

/**
 * Navigation order for different categories
 */
export const NAVIGATION_ORDER = {
  [ROUTE_CATEGORIES.MAIN]: 1,
  [ROUTE_CATEGORIES.INVENTORY]: 2,
  [ROUTE_CATEGORIES.PURCHASES]: 3,
  [ROUTE_CATEGORIES.OBJECTS]: 4,
  [ROUTE_CATEGORIES.SUPPLIERS]: 5,
  [ROUTE_CATEGORIES.USERS]: 6,
  [ROUTE_CATEGORIES.SETTINGS]: 7,
  [ROUTE_CATEGORIES.ARCHIVE]: 8,
  [ROUTE_CATEGORIES.REPORTS]: 9,
  [ROUTE_CATEGORIES.IMPORT]: 10
} as const



